# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-location
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all
  description: A collection of all Backstage entities, except users, groups, and templates
spec:
  targets:
    - ./all-domains.yaml
    - ./all-resources.yaml
    - ./all-systems.yaml
