# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-domain
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: product
  description: 商品
spec:
  owner: product-team
